# 15 test cases
test_cases = [
    {"prompt": "Compute the area under the curve y=x^2 over [0,2]", "expected": "2.67"},
    {"prompt": "What is the volume of the solid obtained by revolving y=x^2 about the x-axis over [0,2]?", "expected": "5.33"},
    {"prompt": "Compute the area under the curve y=3x^3 over [0,1]", "expected": "0.75"},
    {"prompt": "What is the volume of the solid obtained by revolving y=3x^3 about the x-axis over [0,1]?", "expected": "0.60"},
    {"prompt": "Find the area between the curves y=x^2 and y=2x over [0,1]", "expected": "0.33"},
    {"prompt": "Compute the area under the curve y=sin(x) over [0,pi]", "expected": "2.00"},
    {"prompt": "What is the volume of the solid obtained by revolving y=sin(x) about the x-axis over [0,pi]?", "expected": "4.93"},
    {"prompt": "Find the area under the curve y=e^x over [0,1]", "expected": "1.72"},
    {"prompt": "Compute the area between y=e^x and y=x over [0,1]", "expected": "0.95"},
    {"prompt": "What is the volume of the solid obtained by revolving y=x^3 about the y-axis over [0,2]?", "expected": "50.27"},
    {"prompt": "Find the area under the curve y=ln(x) over [1,e]", "expected": "1.00"},
    {"prompt": "Compute the area under the curve y=1/x over [1,2]", "expected": "0.69"},
    {"prompt": "What is the volume of the solid obtained by revolving y=ln(x) about the x-axis over [1,e]?", "expected": "4.39"},
    {"prompt": "Find the area between the curves y=cos(x) and y=sin(x) over [0,pi/4]", "expected": "0.11"},
    {"prompt": "Compute the volume of the solid obtained by revolving y=1/(x^2) about the x-axis over [1,2]", "expected": "0.20"},
    # {"prompt": "Find the area under the curve y=cos(x) over [0,pi/2]", "expected": "1.00"},
    # {"prompt": "Compute the area under the curve y=x^4 over [0,1]", "expected": "0.20"},
    # {"prompt": "What is the volume of the solid obtained by revolving y=sqrt(x) about the x-axis over [0,4]?", "expected": "21.33"},
    # {"prompt": "Compute the area under the curve y=2^x over [0,1]", "expected": "1.44"},
    # {"prompt": "What is the volume of the solid obtained by revolving y=2^x about the x-axis over [0,1]?", "expected": "4.44"},
    # {"prompt": "Find the area under the curve y=tan(x) over [0,pi/4]", "expected": "0.35"},
    # {"prompt": "Compute the area between the curves y=ln(x) and y=1/x over [1,e]", "expected": "0.72"},
    # {"prompt": "What is the volume of the solid obtained by revolving y=1/(1+x^2) about the x-axis over [0,1]?", "expected": "3.14"},
    # {"prompt": "Find the area under the curve y=arctan(x) over [0,1]", "expected": "0.66"},
    # {"prompt": "Compute the volume of the solid obtained by revolving y=arctan(x) about the x-axis over [0,1]?", "expected": "0.44"},
    # {"prompt": "Find the area under the curve y=x^2+1 over [0,1]", "expected": "1.33"},
    # {"prompt": "Compute the area under the curve y=1/(1+x^2) over [0,1]", "expected": "0.88"}
]